language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: GYqAE06goH3ucSOv4ff51OJxoB9fg87IbCSK12FamgYvYxhEmtNwtgdpe0Bc5UKrTJ9yc6PQ/9vJ3IF6Lx9sMGY7kf77lE1hU0rCkZywfyEmPtdFBTJz0OsVT98FUG6nFPap7g0Y//dGeUv+ssGIjll51kZMNFXRcQDOsXDrfgzA231t42yx+mpfLA48cNLfnTXOvuUVH/uXbI8b2OUo7qpUy/jdnbB7GVXx9oQEhPflh1VFhZJ8LI9TkLmqibYcIlcT8Cuv8hm67tHh3l8qtQU2QZ/JE7j8LmXD/XWsBTBljkc2inB8JxcwQhNqt00xyadgo7iiqs2KBlamdix5tx18XTjnGDPE2IVLG8keeD9DwlEccRMAe7amdde3gp0Vcb30d36Qiir4jXpKFXXASb92jRh9pIxdF7427iIZCDgAmGSMIeq+zkk1xdAZ4zL3UORxy09EbUevISn1G26DRPjb27tKHPqV7p/YfB8dIUPbg3AF55hya8D+fcMKRRBA25AoaXE41fOuL0o7CzfYVmUi2wTLssC+3FNBdwHHUJ8+5vWjdZVeJiH5E9zOJCSPxueJoNG+gIn9y1MrCRadzdOHcuHv3rEqvAkgyatspIJmXyX8rNggAOvpVdzH7o1d1qWNzmKKneIx2p1fWEK/8dCGsGDF7HBkEB8WJpJnIJY=
  app: obscure-retreat-46503
  on:
    repo: complicationlamp/flashcard-react-app-client
