language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: Jf0P8/cQ9vp5+mAgm9d487jb746o80QjciqP/oTaYX72yJPbnq4NR92CtVWKRD8WojfbN6IUQCfvqHSJSoVQQGTfGoZo/AHnSPSqsVR381oZltoQSIZHPD8zrcpeNIdygeiQ2NuCEhh3bVXHB60pIQZFoHKuz8q3zH6q6IgHNrc/30nCFSCbTGn/+K2BKI5HDNXplsMZV+JN4xHP/idmWBOJYrBWXylDqCE6G/Gc7ucsdepxrWrxPNyWdlzCVPi4neAPQlcRszScOrisU5bvmZXgyZB7xRgAa6+8oTo41M8RsO8kWwwjY3nj5UeG111DgU/bYF6uqT6wHODbBRRdHqfDkHwt0WmqZVWiT8R/Vz+2LvG3mnp37DEqanZjo9RsTj7273ilipP8uycVCoCIQISPlan0wyIX3PcqDPWB9tN6RLZvMNQEmbhnwjDEOHCME+ER2FZBz4BUv3IxHo7/V0jhjrPGScMp0J6fBM1OWfjCLQmT0EHCT7la5LdS4LkuCJSEmA8M+9sr36U+t6AAA/0Fvj863ak7HGoYrffWEEYf/gmD5qN2/X9DHfmF61vvOAz+o4lo9d61brtYY3VxU5M+7NjMvYyRvQIgCSvO/zoonQPyiCNnRjAcosN78zJCtn0urvP2S3+njovRUqVHP5sYeF4PVX8CADdZ9cmF0Lk=
  app: cryptic-dusk-34746
  on:
    repo: complicationlamp/flashcard-react-app-client
