language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: mH7k7JZKR3lKNDvGhs7XBhOqaFaSP0zFjFhGA/XSI5wuGRz0w22VuivVhF0HUzX9cYJePm5xFhwJ/YLTAfAq9PSC8GsrfnuU8zlWmMWeugMmvrl5JQRcPUpRmJqFrh9WWgfjDR3O1tYjHXKN8oczwtux8LpROWsS5eiWewxgAxdEWolj+C5CJywo+B4QcVjSqN9ONKhusmSKuL0Et4dKaW/l8vUyy6SmnEWjyyXBF9380oO3R+fHoThi1M/lUnXB9Dp8dSeBAptLT1LXnEr0IoE2gMwSDwMKzbu4GmpO/gLsQzAjpXldh9eUv6QlhGE8EWxBh2F7o9Dw8mgJLXxtmX39KLwT4E+QzestUj/LbvU2CHqm/KBGYBQtEYUEdhQOmZbswe1YV993l28Sw6SFxSeDdkfbsDqaFe0nyVGGgaUshlZYtvSpdnu2CTxEDBVeH7UeBmyPk2+se5YMTDO+lZbWMCD8LHsktybygIcJHNpoI4FqKZkoLQzXerYZlr4bZetDygWihgF9z+8LtaTu5cTvZTK7FeqjZ7CXAeHbU6YulTBDSLFMQoVArJpuhQCAOXCAlKxcfpy6uzodElSnbv9TYOS6YT371zOGY8KOefDeuHD0HTCRrA5rz4PPo3i2JfCCdSAW9gnwUvtPHpFmdJqOXBm9xlwrNfk0mvndu84=
  app: cryptic-dusk-34746
  on:
    repo: complicationlamp/flashcard-react-app-client
